version: '3'

services:
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD
      timeout: 20s
      retries: 10

volumes:
  bundle:
  mysql-data:
